import FaviconLinks from "@/components/Common/FaviconLinks";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <FaviconLinks />
        {children}
      </body>
    </html>
  );
}
